MediaPortal/MediaPortal-1

- mediaportal/Configuration/Sections/Remote.cs
Change-Id: I32c39ac7cf5ca2fc1380fe123f00ecf2f444d324
> MP1-4650: Renamed remote configuration section.

- mediaportal/RemotePlugins/InputMapper/HidInputMappingForm.cs
Repeat attributes are now persisted through customization.
> MP1-4763: Fixing missing HID button repeat attributes after customization

- mediaportal/Databases/Video/IMDBMovie.cs
- mediaportal/MediaPortal.Base/language/strings_en.xml
- mediaportal/MediaPortal.Base/language/strings_ru.xml
- mediaportal/MediaPortal.Base/scripts/MovieInfo/TMDB_de.csscript
- mediaportal/WindowPlugins/GUIVideos/GUIVideoTitle.cs
MP1-4863: Add New Collection from MP GUI
MP1-4863: Remove Selected Collection from MP GUI
MP1-4863: When delete Movie from User Group/Collection, if more then one User Group/Collection show Dialog
MP1-4863: Add to TMDB_DE grabber Awards and MPAA Text support (1.17 and >)
MP1-4863: New Language id 1337 and 1338 in EN,RU
> MP1-4863: MyVideo_bug_fixes_and_Improvements

- mediaportal/Core/guilib/Functions.cs
- mediaportal/Core/guilib/GUIInfoManager.cs
- string.valueequals
- string.valuecontains
- string.valuestarts
Changes in the results caching mechanism.
> MP1-4831-V3: Add New function:

- TvEngine3/TVLibrary/TvPlugin/TvPlugin/RadioRecorded.cs
- TvEngine3/TVLibrary/TvPlugin/TvPlugin/RadioSearch.cs
- TvEngine3/TVLibrary/TvPlugin/TvPlugin/TVConflicts.cs
- TvEngine3/TVLibrary/TvPlugin/TvPlugin/TVPriorities.cs
- TvEngine3/TVLibrary/TvPlugin/TvPlugin/TVProgramInfo.cs
- TvEngine3/TVLibrary/TvPlugin/TvPlugin/TVRecordedInfo.cs
- TvEngine3/TVLibrary/TvPlugin/TvPlugin/TVScheduler.cs
- TvEngine3/TVLibrary/TvPlugin/TvPlugin/TVSearch.cs
- TvEngine3/TVLibrary/TvPlugin/TvPlugin/TVUtil.cs
- TvEngine3/TVLibrary/TvPlugin/TvPlugin/TvRecorded.cs
Here's the improvement for showing the year if different than current
> Feat xxx add year to labels

- mediaportal/WindowPlugins/GUIVideos/GUIVideoInfo.cs
Added:
GUICheckButton for Awards (50) and Text Parental Rating (52).
GUITextScrollUpControl for Awards (51) and Text Parental Rating (53).
> MP1-4895: Add new controls in VideoInfo

- mediaportal/Core/guilib/GUIInfoManager.cs
SpeedUP for GUIInfoManager TranslateSingleString function (in synthetic test more then twice)
> MP1-4899 Resume skin function system.idletime (cosmetic and speedup)

- TvEngine3/TVLibrary/TVServer.Base/TuningParameters/dvbip/UK.Freeview.m3u
- TvEngine3/TVLibrary/TVServer.Base/TuningParameters/dvbt/UK.Angus.xml
- TvEngine3/TVLibrary/TVServer.Base/TuningParameters/dvbt/UK.Beacon Hill.xml
- TvEngine3/TVLibrary/TVServer.Base/TuningParameters/dvbt/UK.Black Hill.xml
- TvEngine3/TVLibrary/TVServer.Base/TuningParameters/dvbt/UK.Bristol Ilchester Crescent.xml
- TvEngine3/TVLibrary/TVServer.Base/TuningParameters/dvbt/UK.Bristol King's Weston Hill.xml
- TvEngine3/TVLibrary/TVServer.Base/TuningParameters/dvbt/UK.Caradon Hill.xml
- TvEngine3/TVLibrary/TVServer.Base/TuningParameters/dvbt/UK.Craigkelly.xml
- TvEngine3/TVLibrary/TVServer.Base/TuningParameters/dvbt/UK.Darvel.xml
- TvEngine3/TVLibrary/TVServer.Base/TuningParameters/dvbt/UK.Durris.xml
- TvEngine3/TVLibrary/TVServer.Base/TuningParameters/dvbt/UK.Ferryside.xml
- TvEngine3/TVLibrary/TVServer.Base/TuningParameters/dvbt/UK.Huntshaw Cross.xml
- TvEngine3/TVLibrary/TVServer.Base/TuningParameters/dvbt/UK.Ivybridge.xml
- TvEngine3/TVLibrary/TVServer.Base/TuningParameters/dvbt/UK.Kilvey Hill.xml
- TvEngine3/TVLibrary/TVServer.Base/TuningParameters/dvbt/UK.Llanddona.xml
- TvEngine3/TVLibrary/TVServer.Base/TuningParameters/dvbt/UK.Long Mountain.xml
- TvEngine3/TVLibrary/TVServer.Base/TuningParameters/dvbt/UK.Mendip.xml
- TvEngine3/TVLibrary/TVServer.Base/TuningParameters/dvbt/UK.Moel-y-Parc.xml
- TvEngine3/TVLibrary/TVServer.Base/TuningParameters/dvbt/UK.Plympton.xml
- TvEngine3/TVLibrary/TVServer.Base/TuningParameters/dvbt/UK.Redruth.xml
- TvEngine3/TVLibrary/TVServer.Base/TuningParameters/dvbt/UK.Rosneath.xml
- TvEngine3/TVLibrary/TVServer.Base/TuningParameters/dvbt/UK.Sudbury.xml
- TvEngine3/TVLibrary/TVServer.Base/TuningParameters/dvbt/UK.Wenvoe.xml
More tuning parameter updates for the UK, the forum thread is [UK Freeview DVB-T update](https://forum.team-mediaportal.com/threads/uk-freeview-dvb-t-update.137970/).
> UK tuning parameter updates.

- TvEngine3/TVLibrary/TVServer.Base/TuningParameters/dvbt/UK.Beacon Hill.xml
- TvEngine3/TVLibrary/TVServer.Base/TuningParameters/dvbt/UK.Ivybridge.xml
- TvEngine3/TVLibrary/TVServer.Base/TuningParameters/dvbt/UK.Mendip.xml
- TvEngine3/TVLibrary/TVServer.Base/TuningParameters/dvbt/UK.Moel-y-Parc.xml
- TvEngine3/TVLibrary/TVServer.Base/TuningParameters/dvbt/UK.Plympton.xml
Just a cleanup of old tuning details, where retune events have occurred.
> Updated tuning parameters for DVB-T UK

- TvEngine3/TVLibrary/Setup/setup.nsi
- TvEngine3/TVLibrary/TVLibrary/TVLibrary.csproj
- TvEngine3/TVLibrary/TVLibrary/packages.config
- TvEngine3/TVLibrary/TvThumbnails/TvThumbnails.csproj
- TvEngine3/TVLibrary/TvThumbnails/packages.config
- mediaportal/Core/Core.csproj
- mediaportal/Core/packages.config
- mediaportal/Databases/Databases.csproj
- mediaportal/Databases/packages.config
- mediaportal/MediaPortal.Application/PostBuild.bat
- mediaportal/MiniDisplayLibrary/MiniDisplayLibrary.csproj
- mediaportal/MiniDisplayLibrary/packages.config
- mediaportal/Setup/setup.nsi
- mediaportal/Utils/Utils.csproj
- mediaportal/Utils/packages.config
- mediaportal/WindowPlugins/Common.GUIPlugins/Common.GUIPlugins.csproj
- mediaportal/WindowPlugins/Common.GUIPlugins/packages.config
- mediaportal/WindowPlugins/GUIPictures/GUIPictures.csproj
- mediaportal/WindowPlugins/GUIPictures/packages.config
> Update MediaInfo.Wrapper to 19.4.1

- TvEngine3/TVLibrary/Setup/setup.nsi
- TvEngine3/TVLibrary/TVLibrary/TVLibrary.csproj
- TvEngine3/TVLibrary/TVLibrary/packages.config
- TvEngine3/TVLibrary/TvThumbnails/TvThumbnails.csproj
- TvEngine3/TVLibrary/TvThumbnails/packages.config
- mediaportal/Core/Core.csproj
- mediaportal/Core/packages.config
- mediaportal/Databases/Databases.csproj
- mediaportal/Databases/packages.config
- mediaportal/MediaPortal.Application/PostBuild.bat
- mediaportal/MiniDisplayLibrary/MiniDisplayLibrary.csproj
- mediaportal/MiniDisplayLibrary/packages.config
- mediaportal/Setup/setup.nsi
- mediaportal/Utils/Utils.csproj
- mediaportal/Utils/packages.config
- mediaportal/WindowPlugins/Common.GUIPlugins/Common.GUIPlugins.csproj
- mediaportal/WindowPlugins/Common.GUIPlugins/packages.config
- mediaportal/WindowPlugins/GUIPictures/GUIPictures.csproj
- mediaportal/WindowPlugins/GUIPictures/packages.config
Reverts MediaPortal/MediaPortal-1#180
Plz make PullRequest to https://github.com/MediaPortal/MediaPortal-1/tree/MP1-4972-Update_MediaInfo_Wrapper
> Revert "Update MediaInfo.Wrapper to 19.4.1"

- mediaportal/Core/Player/StreamBufferPlayer9.cs
last used position is remembered for dvr-ms
> Fix for MP1-4392

- mediaportal/Databases/Pictures/SqlLite/PictureDatabaseSqlLite.cs
- mediaportal/MediaPortal.Base/skin/Titan/mypics.hiddenmenu.xml
Fixed navigation issues in titan
> Removed some unneeded checks

- Common-MP-TVE3/PowerScheduler.Interfaces/WaitableTimer.cs
- TvEngine3/TVLibrary/Plugins/PowerScheduler/PowerScheduler.cs
Details - https://github.com/MediaPortal/MediaPortal-1/pull/70
> Allow other plugins reading the next PS wakeup time

- mediaportal/Core/Core.csproj
- mediaportal/Core/packages.config
- mediaportal/Databases/Databases.csproj
- mediaportal/Databases/packages.config
- mediaportal/MediaPortal.Application/PostBuild.bat
- mediaportal/MiniDisplayLibrary/MiniDisplayLibrary.csproj
- mediaportal/MiniDisplayLibrary/packages.config
- mediaportal/Setup/setup.nsi
- mediaportal/Utils/Utils.csproj
- mediaportal/Utils/packages.config
- mediaportal/WindowPlugins/Common.GUIPlugins/Common.GUIPlugins.csproj
- mediaportal/WindowPlugins/Common.GUIPlugins/packages.config
- mediaportal/WindowPlugins/GUIPictures/GUIPictures.csproj
- mediaportal/WindowPlugins/GUIPictures/packages.config
Reverts MediaPortal/MediaPortal-1#210
> Revert "MP1-4998: Update MediaInfo.Wrapper to 19.9.2"

- README.md
- appveyor.yml
- Add README.md
- Add appveyor.yml
> Add README.md and appveyor.yml

- mediaportal/MediaPortal.Base/skin/Titan/DialogPinCode.xml
Change PinCode images in Titan skin to black and blue values.
White is currently specified but it does not exist.
> PinCode images changed to black and blue

- mediaportal/MediaPortal.Base/skin/Titan/DialogPinCode.xml
https://github.com/MediaPortal/MediaPortal-1/pull/299
> MP1.34-Pre: Titan - PinCode images changed to black and blue

- mediaportal/MediaPortal.Base/skin/Titan/DialogPinCode.xml
- mediaportal/MediaPortal.Base/skin/Titan/DialogVideoInfo.xml
- mediaportal/MediaPortal.Base/skin/Titan/common.overlay.xml
- mediaportal/MediaPortal.Base/skin/Titan/dialogGeneralRating.xml
- mediaportal/MediaPortal.Base/skin/Titan/mytvrecordedtv.xml
- mediaportal/MediaPortal.Base/skin/Titan/myvideo.mediainfo.xml
- mediaportal/MediaPortal.Base/skin/Titan/videoFullScreen.xml
- mediaportal/MediaPortal.Base/skin/Titan/videoOSD.xml
Moving files from MePo theme Titan skin with FanartHandler support
> Moving files from MePo theme Titan skin with FanartHandler support

- mediaportal/MediaPortal.Base/skin/Titan/mytvrecordedtv.xml
Drivespace removed and if required can be added back in
> Restore original mytvrecordedtv.xml file

- Tools/MediaPortal.DeployTool/Utils.cs
Reverts MediaPortal/MediaPortal-1#423
> Revert "Test minor version bump"

- Common-MP-TVE3/SolutionInfo.cs
- Tools/InstallationScripts/include/MediaPortalCurrentVersion.nsh
- Tools/MediaPortal.DeployTool/Utils.cs
- mediaportal/Configuration/App.config
- mediaportal/MediaPortal.Application/App.config
Reverts MediaPortal/MediaPortal-1#420
> Revert "MP1.38.Update.1: Minor version bump"
